steps:
  # Build the Docker image test
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hip-girder-402314/anand-assign2/flaskapp:${SHORT_SHA}', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/hip-girder-402314/anand-assign2/flaskapp:${SHORT_SHA}']

  # Update the Compute Engine instance with the new image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'update-container', 'my-instance', '--container-image', 'gcr.io/hip-girder-402314/anand-assign2/flaskapp:${SHORT_SHA}', '--zone', 'us-central1-a']
options:
  # Set defaultLogsBucketBehavior to REGIONAL_USER_OWNED_BUCKET
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
images:
  - 'gcr.io/hip-girder-402314/anand-assign2/flaskapp:${SHORT_SHA}'
